apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-livraria
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: api-livraria
    template:
      metadata: 
        labels:
          app: api-livraria
      spec:
        containers:
        - name: api-livraria
          image: harbor.homelab.local/library/api-livraria:latest
          imagePullPOlicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: ConnectionStrings__OracleConnection
            value: "User Id=project_api;Password=30317512;Data Source=192.168.1.8:1521/XEPDB1;"
---
apiVersion: v1
kind: Service
metadata:
  name: api-livraria-Service
  namespace: default
spec:
  selector:
    app: api-livraria
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-livraria-Ingress
  namespace: default
spec:
  rules:
  - host: livraria.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-livraria-service
            port:
              number: 80